### PR TITLE
feat: Add CODEOWNERS

### PR DESCRIPTION
**Pull request by Kouteki**
Current state

- No code owners for docs.gno.land - open PRs aren't automatically assigning reviewers

Desired state

- Tech staff team are code owners. Open PRs automatically assign reviewers

AC

- Add @gnolang/tech-staff as docs.gno.land code owners

### CODE REVIEW

**Comment by alexiscolin** [comment]
@Kouteki @leohhhn @zivkovicmilos Do you think we can add me as co-owner for `/docusaurus` folder? So, I would be pinged for any update that can occur in this folder that I usually maintain.

**Comment by leohhhn** [comment]
Please also add  @gnolang/devrels to codeowners

**Comment by zivkovicmilos** [comment]
> Please also add @gnolang/devrels to codeowners

@leohhhn 

We don't believe the DevRel team should be a CODEOWNER for the core team documentation, hence this PR that doesn't include the DevRel team. Core team documentation should stay within the core team, and be managed by the core team, while the DevRel team can advise

**Comment by Kouteki** [comment]
@alexiscolin added you as the code owner, and also as the PR reviewer :)

**Review by alexiscolin — APPROVED** [review]
Thank you 🙏

**Pull request merged**
